### ISSUE TITLE
Redmine - Git:branch - Skip content contained in square brackets

### ISSUE THREAD

**Issue by Fatal-Error** [sparkfabrik/sparktool#53]
**Scenario**: I want to create a git branch using redmine:git:branch command
**Given**: I have an issue with title `EE-659 - [Implementation of the new Homepage] Add display type "Call to Action"` and id `8991`
**When**: I run command `spark redmine:git:branch 8991`
**Then**: I can see a new branch has been created with the following name:
`features/EE-659_8991_add_display_type_call_to_action`

**Comment by alessiopiazza** [comment]
i just tried a `--dry-run` and it seems that this issue is no longer valid

``````
I will execute: git checkout develop
I will execute: git checkout -b feature/EE-659_8991_implementation_of_the_new_homepage_add_display_type_call_to_action
I will execute: git push --set-upstream origin feature/EE-659_8991_implementation_of_the_new_homepage_add_display_type_call_to_action```
``````

**Comment by paolomainardi** [comment]
@alessiopiazza can i close this issue ?

**Comment by alessiopiazza** [comment]
@paolomainardi i would say yes

**Comment by paolomainardi** [comment]
thanks!
